spring:
  application:
    name: service-registry


logging:
  level:
    root: info

registration: https://raw.githubusercontent.com/jfbramlett/service-registry/master/src/main/resources/services.properties